name: Validate and Release connector
on:
  push:
    branches:
      - ci_testing
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CrateDB connector
        uses: actions/checkout@v4
        with:
          path: cratedb-tableau-connector

      - name: Checkout Tableau Connector SDK
        uses: actions/checkout@v4
        with:
          repository: tableau/connector-plugin-sdk
          ref: tableau-2024.2