name: Validate and Release connector
on:
  push:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tableau Connector SDK
        uses: actions/checkout@v4
        with:
          repository: tableau/connector-plugin-sdk
          ref: tableau-2024.2

      - name: Checkout CrateDB connector
        uses: actions/checkout@v4
        with:
          path: cratedb-tableau-connector

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Set up Tableau connector packager
        working-directory: connector-packager
        run: |
          python -m venv .venv
          source ./.venv/bin/activate
          python -m pip install setuptools
          python setup.py install

      - name: Validate connector
        working-directory: connector-packager
        run: |
          echo Workflow: Validating connector
          source ./.venv/bin/activate
          python -m connector_packager.package --validate-only $GITHUB_WORKSPACE/cratedb-tableau-connector/cratedb_jdbc

      - name: Build connector
        working-directory: connector-packager
        run: |
          echo Workflow: Building connector connector 
          source ./.venv/bin/activate
          python -m connector_packager.package $GITHUB_WORKSPACE/cratedb-tableau-connector/cratedb_jdbc
          ls
          TACO_FILE_PATH=$(find "$(pwd/packaged-connector -P)" -name "*.taco" | head -n 1)
          echo $TACO_FILE_PATH
          echo "TACO_FILE_PATH=TACO_FILE_PATH" >> $GITHUB_ENV