name: Validate and Release connector
on:
  push:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CrateDB connector
        uses: actions/checkout@v4
        with:
          path: cratedb-tableau-connector

      - name: Checkout Tableau Connector SDK
        uses: actions/checkout@v4
        with:
          repository: tableau/connector-plugin-sdk
          ref: tableau-2024.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Package the connector
        working-directory: connector-packager
        run: |
          python -m venv .venv
          source ./.venv/bin/activate
          python -m pip install setuptools
          python setup.py install
          pwd
          ls
          ls ..
          echo $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE
          python -m connector_packager.package ./cratedb_jdbc
